name: Unit Tests with Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: PYTHONPATH=$(pwd) pytest --cov=myapp --cov-report=xml tests/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Checkout branch
        run: |
          git fetch --all
          git checkout ${{ github.head_ref }} || git checkout main
      - name: Ensure README.md exists and is not empty
        run: |
          if [ ! -e README.md ] || [ ! -s README.md ]; then
            echo "# Project Title\n\n![Build Status](https://github.com/Movchanets/github_actions/actions/workflows/workflow.yaml/badge.svg)\n\n## Description\n\nA brief description of the project." > README.md
            git add README.md
            git commit -m "Initialize README.md with build status badge"
            git push
          else
            echo "README.md already exists and is not empty."
          fi
      - name: Update README.md with build status badge
        run: |
          set -e  # Exit on error
          echo "Updating README.md with build status badge..."
          echo "# Project Title\n\n![Build Status](https://github.com/Movchanets/github_actions/actions/workflows/workflow.yaml/badge.svg)\n\n## Description\n\nA brief description of the project." > README.md
          git add README.md
          git commit -m "Update build status badge" || echo "No changes to commit"
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
